# Generated by Django 3.2.7 on 2022-03-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCysec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'О Cysec',
                'verbose_name_plural': 'О Cysec',
            },
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
