# Generated by Django 4.0.3 on 2022-03-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
