# Generated by Django 3.2.7 on 2022-03-12 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='sunject',
            new_name='subject',
        ),
    ]
