# Generated by Django 4.0.3 on 2022-03-15 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_message_subject'),
        ('home', '0016_rename_sunject_contact_subject'),
    ]

    operations = [
    ]
